In [16]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree

iris = load_iris()
print(iris.feature_names)
print(iris.target_names)

print(iris.data[0])
print(iris.target[0])

#or i in range(len(iris.target)):
 #  print("Example %d : label %s , feature %s"%(i,iris.target[i],iris.data[i]))
    
test_idx = [0,50,100]
#training data
train_target = np.delete(iris.target,test_idx)                  #training data will contain all data except test_idx data
train_data = np.delete(iris.data,test_idx,axis = 0)

#testing data
test_target = iris.target[test_idx]                         #testing data will contain test_idx 3 data sets that are deleted 
test_data = iris.data[test_idx]

clf = tree.DecisionTreeClassifier()
clf.fit(train_data,train_target)

print(test_target)

clf.predict(test_data)


 



['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[5.1 3.5 1.4 0.2]
0
[0 1 2]


array([0, 1, 2])